### ISSUE TITLE
Intermittent Issue - xServer Stuck in IBD Mode

### ISSUE THREAD

**Issue by Gabriel-x42** [x42protocol/x42-Server#18]
Bug Description:
The xServer never leaves the IBD mode.

Steps to reproduce the bug:

01. Open the xServer client
02. Set it up and unlock it.
03. Sometimes the client is completely stuck in IBD mode upon first sync, even while fully synced up.

Screenshots:
![image](https://user-images.githubusercontent.com/59352730/108013839-4759d780-6feb-11eb-8d42-f6d6a9397924.png)

**Comment by psavva** [comment]
@Gabriel-x42 I think this issue is now obsolete
