### ISSUE TITLE
Function Request - xCore Currency Pair Feature

### ISSUE THREAD

**Issue by Gabriel-x42** [x42protocol/x42-Server#21]
Describe the solution you would like:
For the xCore currency pairing feature to be implemented on the xServer interface.

![image](https://user-images.githubusercontent.com/59352730/127613308-81c90cac-b826-4f1e-a111-84e0465de109.png)

**Comment by Gabriel-x42** [comment]
A bounty of 1000 x42 has been added to anyone who delivers the code for this function.
The pull request MUST be approved and merged before the bounty is paid.

**Comment by dimsavva** [comment]
Working on this

**Comment by psavva** [comment]
@dimsavva is this delivered?
Can we close?
